SELECT
  IATA_CODE,
  AIRPORT,
  TYPE,
  SCHEDULED,
  ACTUAL,
  ON_TIME,
  DELAYED,
  DIVERTED,
  CANCELLED,
  DIVERTED_FLIGHTS,
  CANCELLED_FLIGHTS,
  CANCELLED_REASON_A,
  CANCELLED_REASON_B,
  CANCELLED_REASON_C,
  CANCELLED_REASON_D,
  ROUND( ACTUAL/SCHEDULED ,3) AS RATIO_ACTUAL,
  ROUND( ON_TIME/SCHEDULED ,3) AS RATIO_ON_TIME,
  ROUND( DELAYED/SCHEDULED ,3) AS RATIO_DELAYED,
  ROUND( DIVERTED/SCHEDULED ,3) AS RATIO_DIVERTED,
  ROUND( CANCELLED/SCHEDULED ,3) AS RATIO_CANCELLED,
  ROUND( DIVERTED_FLIGHTS/SCHEDULED ,3) AS RATIO_DIVERTED_FLIGHTS,
  ROUND( CANCELLED_FLIGHTS/SCHEDULED ,3) AS RATIO_CANCELLED_FLIGHTS,
  ROUND( CANCELLED_REASON_A/CANCELLED_FLIGHTS ,3) AS RATIO_CANCELLED_REASON_A,
  ROUND( CANCELLED_REASON_B/CANCELLED_FLIGHTS ,3) AS RATIO_CANCELLED_REASON_B,
  ROUND( CANCELLED_REASON_C/CANCELLED_FLIGHTS ,3) AS RATIO_CANCELLED_REASON_C,
  ROUND( CANCELLED_REASON_D/CANCELLED_FLIGHTS ,3) AS RATIO_CANCELLED_REASON_D
FROM (
  SELECT
    MIN(FL.ORIGIN_AIRPORT) AS IATA_CODE,
    MIN(AI.AIRPORT) AS AIRPORT,
    'DEPARTURES' AS TYPE,
    COUNT( FL.SCHEDULED_DEPARTURE ) AS SCHEDULED,
    COUNT( FL.DEPARTURE_TIME ) AS ACTUAL,
    COUNT( CASE WHEN FL.DEPARTURE_DELAY <= 0 THEN FL.DEPARTURE_TIME
      WHEN FL.DEPARTURE_TIME <= FL.SCHEDULED_DEPARTURE THEN FL.DEPARTURE_TIME END ) AS ON_TIME,
    COUNT( CASE WHEN FL.DEPARTURE_DELAY > 0 THEN FL.DEPARTURE_TIME
      WHEN FL.DEPARTURE_TIME > FL.SCHEDULED_DEPARTURE THEN FL.DEPARTURE_TIME END ) AS DELAYED,
    COUNT( CASE WHEN FL.DIVERTED = 1 THEN FL.DEPARTURE_TIME END ) AS DIVERTED,
    COUNT( CASE WHEN FL.CANCELLED = 1 THEN FL.DEPARTURE_TIME END ) AS CANCELLED,
    COUNT( CASE WHEN FL.DIVERTED = 1 THEN FL.DIVERTED END ) AS DIVERTED_FLIGHTS,
    COUNT( CASE WHEN FL.CANCELLED = 1 THEN FL.CANCELLED END ) AS CANCELLED_FLIGHTS,
    COUNT( CASE WHEN FL.CANCELLATION_REASON = 'A' THEN FL.CANCELLATION_REASON END ) AS CANCELLED_REASON_A,
    COUNT( CASE WHEN FL.CANCELLATION_REASON = 'B' THEN FL.CANCELLATION_REASON END ) AS CANCELLED_REASON_B,
    COUNT( CASE WHEN FL.CANCELLATION_REASON = 'C' THEN FL.CANCELLATION_REASON END ) AS CANCELLED_REASON_C,
    COUNT( CASE WHEN FL.CANCELLATION_REASON = 'D' THEN FL.CANCELLATION_REASON END ) AS CANCELLED_REASON_D
  FROM
    `data.flights` AS FL
  INNER JOIN
    `data.airports` AS AI
  ON
    FL.ORIGIN_AIRPORT = AI.IATA_CODE
  WHERE
    FL.ORIGIN_AIRPORT = 'ATL'
  UNION ALL
  SELECT
    MIN(FL.DESTINATION_AIRPORT) AS IATA_CODE,
    MIN(AI.AIRPORT) AS AIRPORT,
    'ARRIVALS' AS TYPE,
    COUNT( FL.SCHEDULED_ARRIVAL ) AS SCHEDULED,
    COUNT( FL.ARRIVAL_TIME ) AS ACTUAL,
    COUNT( CASE WHEN FL.ARRIVAL_DELAY <= 0 THEN FL.ARRIVAL_TIME
      WHEN FL.ARRIVAL_TIME <= FL.SCHEDULED_ARRIVAL THEN FL.ARRIVAL_TIME END ) AS ON_TIME,
    COUNT( CASE WHEN FL.ARRIVAL_DELAY > 0 THEN FL.ARRIVAL_TIME
      WHEN FL.ARRIVAL_TIME > FL.SCHEDULED_ARRIVAL THEN FL.ARRIVAL_TIME END ) AS DELAYED,
    COUNT( CASE WHEN FL.DIVERTED = 1 THEN FL.ARRIVAL_TIME END ) AS DIVERTED,
    COUNT( CASE WHEN FL.CANCELLED = 1 THEN FL.ARRIVAL_TIME END ) AS CANCELLED,
    COUNT( CASE WHEN FL.DIVERTED = 1 THEN FL.DIVERTED END ) AS DIVERTED_FLIGHTS,
    COUNT( CASE WHEN FL.CANCELLED = 1 THEN FL.CANCELLED END ) AS CANCELLED_FLIGHTS,
    COUNT( CASE WHEN FL.CANCELLATION_REASON = 'A' THEN FL.CANCELLATION_REASON END ) AS CANCELLED_REASON_A,
    COUNT( CASE WHEN FL.CANCELLATION_REASON = 'B' THEN FL.CANCELLATION_REASON END ) AS CANCELLED_REASON_B,
    COUNT( CASE WHEN FL.CANCELLATION_REASON = 'C' THEN FL.CANCELLATION_REASON END ) AS CANCELLED_REASON_C,
    COUNT( CASE WHEN FL.CANCELLATION_REASON = 'D' THEN FL.CANCELLATION_REASON END ) AS CANCELLED_REASON_D
  FROM
    `data.flights` AS FL
  INNER JOIN
    `data.airports` AS AI
  ON
    FL.DESTINATION_AIRPORT = AI.IATA_CODE
  WHERE
    FL.DESTINATION_AIRPORT = 'ATL'
)