SELECT
  AI.IATA_CODE,
  AI.AIRPORT,
  COUNT(FL.SCHEDULED_DEPARTURE) AS SCHEDULED_DEPARTURES
FROM
  `data.flights` AS FL
INNER JOIN
  `data.airports` AS AI
ON
  FL.ORIGIN_AIRPORT = AI.IATA_CODE
GROUP BY
  AI.IATA_CODE, AI.AIRPORT
ORDER BY
  SCHEDULED_DEPARTURES DESC
LIMIT
  10