SELECT
  EVENT_DATE,
  SCHEDULED_DEPARTURES,
  ACTUAL_DEPARTURES,
  ON_TIME_DEPARTURES,
  DELAYED_DEPARTURES,
  DIVERTED_DEPARTURES,
  CANCELLED_DEPARTURES,
  ACTUAL_ARRIVALS,
  ON_TIME_ARRIVALS,
  DELAYED_ARRIVALS,
  DIVERTED_ARRIVALS,
  CANCELLED_ARRIVALS,
  DIVERTED_FLIGHTS,
  CANCELLED_FLIGHTS,
  CANCELLED_REASON_A,
  CANCELLED_REASON_B,
  CANCELLED_REASON_C,
  CANCELLED_REASON_D,
  ROUND( 100*ACTUAL_DEPARTURES/SCHEDULED_DEPARTURES ,3) AS PERCENT_ACTUAL_DEPARTURES,
  ROUND( 100*ON_TIME_DEPARTURES/SCHEDULED_DEPARTURES ,3) AS PERCENT_ON_TIME_DEPARTURES,
  ROUND( 100*DELAYED_DEPARTURES/SCHEDULED_DEPARTURES ,3) AS PERCENT_DELAYED_DEPARTURES,
  ROUND( 100*DIVERTED_DEPARTURES/SCHEDULED_DEPARTURES ,3) AS PERCENT_DIVERTED_DEPARTURES,
  ROUND( 100*CANCELLED_DEPARTURES/SCHEDULED_DEPARTURES ,3) AS PERCENT_CANCELLED_DEPARTURES,
  ROUND( 100*ACTUAL_ARRIVALS/SCHEDULED_ARRIVALS ,3) AS PERCENT_ACTUAL_ARRIVALS,
  ROUND( 100*ON_TIME_ARRIVALS/SCHEDULED_ARRIVALS ,3) AS PERCENT_ON_TIME_ARRIVALS,
  ROUND( 100*DELAYED_ARRIVALS/SCHEDULED_ARRIVALS ,3) AS PERCENT_DELAYED_ARRIVALS,
  ROUND( 100*DIVERTED_ARRIVALS/SCHEDULED_ARRIVALS ,3) AS PERCENT_DIVERTED_ARRIVALS,
  ROUND( 100*CANCELLED_ARRIVALS/SCHEDULED_ARRIVALS ,3) AS PERCENT_CANCELLED_ARRIVALS,
  ROUND( 100*DIVERTED_FLIGHTS/SCHEDULED_DEPARTURES ,3) AS PERCENT_DIVERTED_FLIGHTS,
  ROUND( 100*CANCELLED_FLIGHTS/SCHEDULED_DEPARTURES ,3) AS PERCENT_CANCELLED_FLIGHTS,
  ROUND( 100*CANCELLED_REASON_A/CANCELLED_FLIGHTS ,3) AS PERCENT_CANCELLED_REASON_A,
  ROUND( 100*CANCELLED_REASON_B/CANCELLED_FLIGHTS ,3) AS PERCENT_CANCELLED_REASON_B,
  ROUND( 100*CANCELLED_REASON_C/CANCELLED_FLIGHTS ,3) AS PERCENT_CANCELLED_REASON_C,
  ROUND( 100*CANCELLED_REASON_D/CANCELLED_FLIGHTS ,3) AS PERCENT_CANCELLED_REASON_D
FROM (
  SELECT
    DATE(SCHEDULED_DEPARTURE) AS EVENT_DATE,
    COUNT( SCHEDULED_DEPARTURE ) AS SCHEDULED_DEPARTURES,
    COUNT( DEPARTURE_TIME ) AS ACTUAL_DEPARTURES,
    COUNT( CASE WHEN DEPARTURE_DELAY <= 0 THEN DEPARTURE_TIME
      WHEN DEPARTURE_TIME <= SCHEDULED_DEPARTURE THEN DEPARTURE_TIME END) AS ON_TIME_DEPARTURES,
    COUNT( CASE WHEN DEPARTURE_DELAY > 0 THEN DEPARTURE_TIME
      WHEN DEPARTURE_TIME > SCHEDULED_DEPARTURE THEN DEPARTURE_TIME END) AS DELAYED_DEPARTURES,
    COUNT( CASE WHEN DIVERTED = 1 THEN DEPARTURE_TIME END ) AS DIVERTED_DEPARTURES,
    COUNT( CASE WHEN CANCELLED = 1 THEN DEPARTURE_TIME END ) AS CANCELLED_DEPARTURES,
    COUNT( SCHEDULED_ARRIVAL ) AS SCHEDULED_ARRIVALS,
    COUNT( ARRIVAL_TIME ) AS ACTUAL_ARRIVALS,
    COUNT( CASE WHEN ARRIVAL_DELAY <= 0 THEN ARRIVAL_TIME
      WHEN ARRIVAL_TIME <= SCHEDULED_ARRIVAL THEN ARRIVAL_TIME END) AS ON_TIME_ARRIVALS,
    COUNT( CASE WHEN ARRIVAL_DELAY > 0 THEN ARRIVAL_TIME
      WHEN ARRIVAL_TIME > SCHEDULED_ARRIVAL THEN ARRIVAL_TIME END) AS DELAYED_ARRIVALS,
    COUNT( CASE WHEN DIVERTED = 1 THEN ARRIVAL_TIME END ) AS DIVERTED_ARRIVALS,
    COUNT( CASE WHEN CANCELLED = 1 THEN ARRIVAL_TIME END ) AS CANCELLED_ARRIVALS,
    COUNT( CASE WHEN DIVERTED = 1 THEN DIVERTED END ) AS DIVERTED_FLIGHTS,
    COUNT( CASE WHEN CANCELLED = 1 THEN CANCELLED END ) AS CANCELLED_FLIGHTS,
    COUNT( CASE WHEN CANCELLATION_REASON = 'A' THEN CANCELLATION_REASON END ) AS CANCELLED_REASON_A,
    COUNT( CASE WHEN CANCELLATION_REASON = 'B' THEN CANCELLATION_REASON END ) AS CANCELLED_REASON_B,
    COUNT( CASE WHEN CANCELLATION_REASON = 'C' THEN CANCELLATION_REASON END ) AS CANCELLED_REASON_C,
    COUNT( CASE WHEN CANCELLATION_REASON = 'D' THEN CANCELLATION_REASON END ) AS CANCELLED_REASON_D
  FROM
    `data.flights`
  GROUP BY
    EVENT_DATE
)
ORDER BY
  EVENT_DATE ASC